[tools]
go = "1.20"
protoc = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
"go:github.com/vektra/mockery/v2" = "v2.38.0"

[settings]
experimental = true

[tasks.generate]
description = "Generate code from protobuf files"
run = 'protoc -I internal --go_opt=paths=source_relative --go_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config:"./internal" --go-grpc_out=Mgrpc/service_config/service_config.proto=/internal/proto/grpc_service_config,paths=source_relative:"./internal" internal/*.proto'
