with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: true
packages:
  github.com/moveaxlab/go-grpc-server/internal:
    interfaces:
      TestServiceServer:
        config:
